framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    #csrf_protection: ~
    #http_method_override: true

    # uncomment this entire section to enable sessions
    #session:
    #    # With this config, PHP's native session handling is used
    #    handler_id: ~

    #esi: ~
    #fragments: ~
    php_errors:
        log: true

    cache:
        # The app cache caches to the filesystem by default. Other options include:

        # apcu
        # app: cache.adapter.apcu

        # redis
        # app: cache.adapter.redis
        # default_redis_provider: redis://localhost
