framework:
    messenger:
        routing:
            # Route your messages to the senders...
            # 'App\Message\YourMessage': messenger.default_sender

        adapters:
            default: "%env(MESSENGER_ADAPTER_DSN)%"
