framework:
    messenger:
        adapters:
            # Uncomment the following line to enable an adapter named "amqp"
            # amqp: "%env(MESSENGER_ADAPTER_DSN)%"

        routing:
            # Route your messages to the senders...
            # 'App\Message\YourMessage': messenger.sender.amqp
